-- NAZU database setup
-- Run this once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  username text,
  points bigint not null default 0,
  referral_code text unique,
  referred_by text,
  level int not null default 1,
  streak int not null default 0,
  last_checkin date,
  created_at timestamptz not null default now()
);

create table if not exists public.missions (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  reward bigint not null default 10,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.user_missions (
  user_id uuid not null references auth.users(id) on delete cascade,
  mission_id bigint not null references public.missions(id) on delete cascade,
  completed_at timestamptz not null default now(),
  primary key (user_id, mission_id)
);

alter table public.profiles enable row level security;
alter table public.missions enable row level security;
alter table public.user_missions enable row level security;

drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles for select using (auth.uid() = id);

drop policy if exists "profiles own insert" on public.profiles;
create policy "profiles own insert" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "missions public read" on public.missions;
create policy "missions public read" on public.missions for select using (active = true);

drop policy if exists "user missions own read" on public.user_missions;
create policy "user missions own read" on public.user_missions for select using (auth.uid() = user_id);

insert into public.missions (title, description, reward)
select 'Daily Check-in', 'Keep your NAZU streak alive.', 25
where not exists (select 1 from public.missions where title='Daily Check-in');

insert into public.missions (title, description, reward)
select 'Complete your profile', 'Set up your NAZU member profile.', 50
where not exists (select 1 from public.missions where title='Complete your profile');

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, referral_code)
  values (new.id, new.email, 'NAZU-' || upper(substr(replace(new.id::text,'-',''),1,8)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
